package com.omniagent.assistant.model

import com.google.gson.annotations.SerializedName

/**
 * Structured Actions generated by the LLM Reasoning Brain.
 */
sealed class AgentAction {

    data class Click(
        val elementId: Int? = null,
        val coordinateX: Float? = null,
        val coordinateY: Float? = null
    ) : AgentAction()

    data class LongClick(
        val elementId: Int? = null,
        val coordinateX: Float? = null,
        val coordinateY: Float? = null
    ) : AgentAction()

    data class TypeText(
        val elementId: Int? = null,
        val text: String,
        val clearExisting: Boolean = false,
        val pressEnter: Boolean = false
    ) : AgentAction()

    data class Scroll(
        val direction: ScrollDirection,
        val elementId: Int? = null
    ) : AgentAction()

    data class Swipe(
        val startX: Float,
        val startY: Float,
        val endX: Float,
        val endY: Float,
        val durationMs: Long = 300L
    ) : AgentAction()

    data class LaunchApp(
        val packageName: String,
        val appName: String? = null
    ) : AgentAction()

    data class PressKey(
        val key: GlobalKey
    ) : AgentAction()

    data class Wait(
        val durationMs: Long = 1000L
    ) : AgentAction()

    data class Speak(
        val message: String
    ) : AgentAction()

    data class AskConfirmation(
        val question: String,
        val riskLevel: RiskLevel = RiskLevel.MEDIUM
    ) : AgentAction()

    data class Finish(
        val success: Boolean,
        val message: String
    ) : AgentAction()
}

enum class ScrollDirection {
    @SerializedName("up") UP,
    @SerializedName("down") DOWN,
    @SerializedName("left") LEFT,
    @SerializedName("right") RIGHT
}

enum class GlobalKey {
    @SerializedName("back") BACK,
    @SerializedName("home") HOME,
    @SerializedName("recents") RECENTS,
    @SerializedName("notifications") NOTIFICATIONS,
    @SerializedName("enter") ENTER
}

enum class RiskLevel {
    @SerializedName("low") LOW,
    @SerializedName("medium") MEDIUM,
    @SerializedName("high") HIGH // Payments, Deleting Accounts, Purchasing
}

/**
 * Full turn response from LLM
 */
data class AgentDecision(
    @SerializedName("thought") val thought: String,
    @SerializedName("action") val actionType: String,
    @SerializedName("target_id") val targetId: Int? = null,
    @SerializedName("coordinates") val coordinates: List<Float>? = null,
    @SerializedName("text") val text: String? = null,
    @SerializedName("direction") val direction: String? = null,
    @SerializedName("package_name") val packageName: String? = null,
    @SerializedName("key") val key: String? = null,
    @SerializedName("message") val message: String? = null,
    @SerializedName("success") val success: Boolean = true
)
